import jsPDF from "jspdf";

export function downloadReceipt(
  payment: any,
  amount: string,
  category: string
) {
  const pdf = new jsPDF("portrait", "mm", "a4");

  // Colors
  const brass = [201, 138, 44];
  const dark = [30, 30, 30];
  const green = [34, 197, 94];
  const gray = [120, 120, 120];

  // Background
  pdf.setFillColor(250, 250, 248);
  pdf.rect(0, 0, 210, 297, "F");

  // ===========================
  // HEADER
  // ===========================

  // Logo circle
  pdf.setDrawColor(...brass);
  pdf.setLineWidth(0.8);
  pdf.circle(20, 22, 7);

  // Lock
  pdf.setFillColor(...brass);
  pdf.circle(20, 20, 1.6, "F");
  pdf.rect(18.8, 21.5, 2.4, 3.6, "F");

  pdf.setTextColor(...dark);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(24);
  pdf.text("GhostPay", 32, 25);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(...gray);
  pdf.text("Confidential Payment Receipt", 32, 32);

  pdf.setDrawColor(...brass);
  pdf.setLineWidth(0.6);
  pdf.line(15, 40, 195, 40);

  // ===========================
  // VERIFIED BADGE
  // ===========================

  pdf.setFillColor(...green);
  pdf.roundedRect(145, 18, 45, 10, 2, 2, "F");

  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  pdf.text("✓ VERIFIED", 154, 24.8);

  // ===========================
  // PAYMENT INFO
  // ===========================

  let y = 55;

  const row = (label: string, value: string) => {
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.setTextColor(...gray);
    pdf.text(label, 20, y);

    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(...dark);

    const wrapped = pdf.splitTextToSize(value, 110);
    pdf.text(wrapped, 70, y);

    y += Math.max(12, wrapped.length * 6 + 3);

    pdf.setDrawColor(230);
    pdf.line(20, y - 5, 190, y - 5);
  };

  row("Receipt ID", `#${payment.id}`);

  row(
    "Sender",
    `${payment.from.slice(0, 10)}...${payment.from.slice(-6)}`
  );

  row(
    "Recipient",
    `${payment.to.slice(0, 10)}...${payment.to.slice(-6)}`
  );

  row("Amount", amount);

  row("Category", category);

  row(
    "Date",
    new Date(payment.timestamp * 1000).toLocaleDateString()
  );

  row(
    "Time",
    new Date(payment.timestamp * 1000).toLocaleTimeString()
  );

  // ===========================
  // FOOTER BOX
  // ===========================

  pdf.setFillColor(245, 245, 245);
  pdf.roundedRect(20, 225, 170, 42, 3, 3, "F");

  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(...dark);
  pdf.setFontSize(12);

  pdf.text("Verification", 28, 238);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);

  pdf.text(
    [
      "This receipt was generated by GhostPay.",
      "Payment details remain confidential and are only",
      "visible to wallets granted decryption permission",
      "through the iExec Nox confidential protocol.",
    ],
    28,
    246
  );

  // ===========================
  // FOOTER
  // ===========================

  pdf.setDrawColor(...brass);
  pdf.line(15, 280, 195, 280);

  pdf.setFont("helvetica", "italic");
  pdf.setTextColor(...gray);
  pdf.setFontSize(9);

  pdf.text(
    "Powered by GhostPay • Built on Ethereum Sepolia • Secured with iExec Nox",
    20,
    287
  );

  pdf.save(`ghostpay-receipt-${payment.id}.pdf`);
}